### ISSUE TITLE
Add tox configuration for easy testing on multiple Python versions and variants

### ISSUE THREAD

**Issue by agronholm** [marrow/web.template#8]
We should ensure that marrow.templating works smoothly on Python 3.2+ and PyPy as well. Tox should come in handy with that.

**Comment by amcgregor** [comment]
Tox will never be utilized by a Marrow package moving forwards; historical finickiness, breakage, and unnecessary complication.  The Travis configuration needs to be updated to a) eliminate Tox usage, b) include additional environments as needed.  As Python 3.2+ and Pypy are already included, closing this issue, though 3.2 itself will be removed due to lack of upstream support.
